/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncompleteRouteImport } from './routes/incomplete'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IndexRouteImport } from './routes/index'

const IncompleteRoute = IncompleteRouteImport.update({
  id: '/incomplete',
  path: '/incomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/incomplete': typeof IncompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/incomplete': typeof IncompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/incomplete': typeof IncompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/complete' | '/incomplete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complete' | '/incomplete'
  id: '__root__' | '/' | '/complete' | '/incomplete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  IncompleteRoute: typeof IncompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/incomplete': {
      id: '/incomplete'
      path: '/incomplete'
      fullPath: '/incomplete'
      preLoaderRoute: typeof IncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  IncompleteRoute: IncompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
